#!/usr/bin/env node

/**
 * @libra/mcp-server — MCP Server for Libra Design System
 *
 * Exposes Libra's design tokens and component generation to AI agents.
 * Allows AI to generate UI code that follows Libra's design language.
 *
 * Tools:
 *   get_tokens         — Return all CSS custom properties with values
 *   get_semantic_colors — Return the semantic color palette (up/down/ma/etc)
 *   get_typography     — Return font stacks and size scale
 *   get_spacing        — Return spacing scale
 *   get_components     — Return component specs (button/card/table)
 *   generate_css       — Generate a complete tokens.css for a project
 *   generate_component — Generate a React component following Libra design
 *
 * @see https://github.com/goodie1972/libra
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

/* ============================================================
   TOKEN DATA
   ============================================================ */

const TOKENS: Record<string, string> = {
  '--up': '#ef5350', '--down': '#26a69a', '--flat': '#9e9e9e',
  '--up-bg': 'rgba(239,83,80,0.08)', '--down-bg': 'rgba(38,166,154,0.08)',
  '--ma5': '#f8b500', '--ma10': '#4a6cf7', '--ma20': '#9c27b0', '--ma60': '#009688', '--ma120': '#ff7043', '--ma250': '#78909c',
  '--success': '#34a853', '--warning': '#fbbc04', '--error': '#ea4335',
  '--bg-root': '#0c0c0e', '--bg-main': '#0c0c0e', '--bg-card': '#121214',
  '--bg-card-hover': '#18181b', '--bg-input': '#18181b',
  '--border-main': '#1e1e22', '--border-sub': '#161618',
  '--text-primary': '#e8e8ed', '--text-secondary': '#9a9aa0', '--text-tertiary': '#63636a',
  '--accent': '#4a6cf7', '--accent-hover': '#5d7cf9',
  '--font-body': "'Inter', -apple-system, 'PingFang SC', sans-serif",
  '--font-mono': "'JetBrains Mono', 'SF Mono', 'Cascadia Code', monospace",
  '--text-xs': '10px', '--text-sm': '12px', '--text-base': '13px', '--text-md': '14px',
  '--text-lg': '16px', '--text-xl': '20px', '--text-2xl': '24px', '--text-3xl': '32px', '--text-4xl': '40px',
  '--space-1': '4px', '--space-2': '8px', '--space-3': '12px', '--space-4': '16px',
  '--space-5': '24px', '--space-6': '32px', '--space-7': '48px', '--space-8': '64px',
  '--btn-radius': '8px', '--card-radius': '10px',
};

const LIGHT_TOKENS: Record<string, string> = {
  '--bg-root': '#f5f5f7', '--bg-main': '#f5f5f7', '--bg-card': '#ffffff',
  '--bg-card-hover': '#f0f0f2', '--bg-input': '#eaeaee',
  '--border-main': '#d4d4d8', '--border-sub': '#e8e8ec',
  '--text-primary': '#0d0d12', '--text-secondary': '#6e6e78', '--text-tertiary': '#8e8e98',
  '--accent': '#533afd', '--accent-hover': '#4527e0',
  '--btn-radius': '20px', '--card-radius': '12px',
};

/* ============================================================
   COMPONENT GENERATORS
   ============================================================ */

function generateCSS(): string {
  return `/* Libra Design System — Auto-generated by @libra/mcp-server */
:root {
  --up: #ef5350; --down: #26a69a; --flat: #9e9e9e;
  --up-bg: rgba(239,83,80,0.08); --down-bg: rgba(38,166,154,0.08);
  --ma5: #f8b500; --ma10: #4a6cf7; --ma20: #9c27b0; --ma60: #009688;
  --success: #34a853; --warning: #fbbc04; --error: #ea4335;

  --bg-root: #0c0c0e; --bg-main: #0c0c0e; --bg-card: #121214;
  --bg-card-hover: #18181b; --bg-input: #18181b;
  --border-main: #1e1e22; --border-sub: #161618;
  --text-primary: #e8e8ed; --text-secondary: #9a9aa0; --text-tertiary: #63636a;
  --accent: #4a6cf7; --accent-hover: #5d7cf9;

  --font-body: 'Inter', -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif;
  --font-mono: 'JetBrains Mono', 'SF Mono', 'Cascadia Code', monospace;

  --text-xs: 10px; --text-sm: 12px; --text-base: 13px; --text-md: 14px;
  --text-lg: 16px; --text-xl: 20px; --text-2xl: 24px; --text-3xl: 32px; --text-4xl: 40px;

  --space-1: 4px; --space-2: 8px; --space-3: 12px; --space-4: 16px;
  --space-5: 24px; --space-6: 32px; --space-7: 48px; --space-8: 64px;

  --btn-radius: 8px; --card-radius: 10px;
  --card-shadow: none; --card-border: 1px solid var(--border-main);
}`;
}

function generateButton(): string {
  return `import { cva, type VariantProps } from "class-variance-authority";

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-[var(--btn-radius)] text-[13px] font-medium transition-all duration-200 focus-visible:outline-hidden disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 hover:-translate-y-[1px]",
  {
    variants: {
      variant: {
        default: "bg-[var(--accent)] text-white hover:bg-[var(--accent-hover)]",
        secondary: "bg-transparent text-[var(--text-primary)] border border-[var(--border-main)] hover:border-[var(--accent)]",
        ghost: "bg-transparent text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-card-hover)]",
        danger: "bg-[var(--error)] text-white hover:opacity-90",
      },
      size: {
        default: "h-9 px-[18px] py-2",
        sm: "h-8 px-3 text-[12px]",
        lg: "h-10 px-6 text-[14px]",
        icon: "h-8 w-8",
      },
    },
    defaultVariants: { variant: "default", size: "default" },
  }
);`;
}

function generateCard(): string {
  return `import type { HTMLAttributes } from "react";

function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn(
        "rounded-[var(--card-radius)] border-[var(--card-border)] bg-[var(--bg-card)] shadow-[var(--card-shadow)] p-5 hover:bg-[var(--bg-card-hover)] hover:border-[var(--accent)] transition-all duration-300",
        className
      )}
      {...props}
    />
  );
}`;
}

/* ============================================================
   MCP SERVER
   ============================================================ */

const server = new Server(
  { name: '@libra/mcp-server', version: '0.1.0' },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: 'get_tokens',
      description: 'Return all Libra design tokens (CSS custom properties)',
      inputSchema: {
        type: 'object',
        properties: {
          mode: { type: 'string', enum: ['dark', 'light'], description: 'Theme mode (default: dark)' },
        },
      },
    },
    {
      name: 'get_semantic_colors',
      description: 'Return semantic colors: up/down, MA lines, functional colors',
      inputSchema: { type: 'object', properties: {} },
    },
    {
      name: 'get_typography',
      description: 'Return font stacks and size scale',
      inputSchema: { type: 'object', properties: {} },
    },
    {
      name: 'get_spacing',
      description: 'Return spacing scale (4px baseline)',
      inputSchema: { type: 'object', properties: {} },
    },
    {
      name: 'get_components',
      description: 'Return component specifications (button, card, table)',
      inputSchema: {
        type: 'object',
        properties: {
          component: { type: 'string', enum: ['button', 'card', 'table', 'all'], description: 'Component name (default: all)' },
        },
      },
    },
    {
      name: 'generate_css',
      description: 'Generate a complete tokens.css file for Libra design system',
      inputSchema: { type: 'object', properties: {} },
    },
    {
      name: 'generate_component',
      description: 'Generate a React component following Libra design language',
      inputSchema: {
        type: 'object',
        properties: {
          component: { type: 'string', enum: ['button', 'card'], description: 'Component to generate' },
        },
        required: ['component'],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
    case 'get_tokens': {
      const mode = (args?.mode as string) || 'dark';
      const palette = mode === 'light' ? { ...TOKENS, ...LIGHT_TOKENS } : TOKENS;
      return {
        content: [{ type: 'text', text: JSON.stringify(palette, null, 2) }],
      };
    }

    case 'get_semantic_colors': {
      const semantic = {
        up: TOKENS['--up'],
        down: TOKENS['--down'],
        flat: TOKENS['--flat'],
        ma_lines: { ma5: TOKENS['--ma5'], ma10: TOKENS['--ma10'], ma20: TOKENS['--ma20'], ma60: TOKENS['--ma60'] },
        functional: { success: TOKENS['--success'], warning: TOKENS['--warning'], error: TOKENS['--error'] },
      };
      return { content: [{ type: 'text', text: JSON.stringify(semantic, null, 2) }] };
    }

    case 'get_typography': {
      const typography = {
        fonts: { body: TOKENS['--font-body'], mono: TOKENS['--font-mono'] },
        sizes: {
          xs: TOKENS['--text-xs'], sm: TOKENS['--text-sm'], base: TOKENS['--text-base'],
          md: TOKENS['--text-md'], lg: TOKENS['--text-lg'], xl: TOKENS['--text-xl'],
          '2xl': TOKENS['--text-2xl'], '3xl': TOKENS['--text-3xl'], '4xl': TOKENS['--text-4xl'],
        },
        rule: 'All numeric values must use mono font with tabular-nums',
      };
      return { content: [{ type: 'text', text: JSON.stringify(typography, null, 2) }] };
    }

    case 'get_spacing': {
      const spacing = {
        baseline: '4px',
        scale: {
          '--space-1': TOKENS['--space-1'], '--space-2': TOKENS['--space-2'],
          '--space-3': TOKENS['--space-3'], '--space-4': TOKENS['--space-4'],
          '--space-5': TOKENS['--space-5'], '--space-6': TOKENS['--space-6'],
          '--space-7': TOKENS['--space-7'], '--space-8': TOKENS['--space-8'],
        },
      };
      return { content: [{ type: 'text', text: JSON.stringify(spacing, null, 2) }] };
    }

    case 'get_components': {
      const component = (args?.component as string) || 'all';
      const specs: Record<string, string> = {};

      if (component === 'all' || component === 'button') {
        specs.button = `4 variants: primary(bg:--accent), secondary(border:--border-main), ghost(transparent), danger(bg:--error). Radius: var(--btn-radius).`;
      }
      if (component === 'all' || component === 'card') {
        specs.card = `bg:--bg-card, border:--border-main, radius:--card-radius. Hover shifts bg and border to accent.`;
      }
      if (component === 'all' || component === 'table') {
        specs.table = `Headers: 10px uppercase --text-tertiary. Cells: 13px. Numeric: right-align mono tabular-nums. Change: --up/--down colored.`;
      }

      return { content: [{ type: 'text', text: JSON.stringify(specs, null, 2) }] };
    }

    case 'generate_css': {
      return { content: [{ type: 'text', text: generateCSS() }] };
    }

    case 'generate_component': {
      const comp = args?.component as string;
      const code = comp === 'button' ? generateButton() : comp === 'card' ? generateCard() : 'Unknown component';
      return { content: [{ type: 'text', text: code }] };
    }

    default:
      throw new Error(`Unknown tool: ${name}`);
  }
});

// Start server
const transport = new StdioServerTransport();
await server.connect(transport);
