// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type WinRateCardProps struct {
	WinRate   float64
	WinCount  int
	LossCount int
}

func WinRateCard(props WinRateCardProps, attrs templ.Attributes) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t.libra-winrate {\n\t\t\tbackground-color: var(--bg-card);\n\t\t\tborder: 1px solid var(--border-main);\n\t\t\tborder-radius: var(--card-radius);\n\t\t\tpadding: var(--space-4);\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\talign-items: center;\n\t\t}\n\t\t.libra-winrate__ring {\n\t\t\tposition: relative;\n\t\t\twidth: 120px;\n\t\t\theight: 120px;\n\t\t\tmargin-bottom: var(--space-3);\n\t\t}\n\t\t.libra-winrate__svg {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\ttransform: rotate(-90deg);\n\t\t}\n\t\t.libra-winrate__center {\n\t\t\tposition: absolute;\n\t\t\tinset: 0;\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\talign-items: center;\n\t\t\tjustify-content: center;\n\t\t}\n\t\t.libra-winrate__percent {\n\t\t\tfont-family: var(--font-mono);\n\t\t\tfont-size: 24px;\n\t\t\tfont-weight: var(--weight-bold);\n\t\t\tcolor: var(--up);\n\t\t\tfont-variant-numeric: tabular-nums;\n\t\t}\n\t\t.libra-winrate__counts {\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tgap: var(--space-3);\n\t\t\tfont-size: var(--text-sm);\n\t\t}\n\t\t.libra-winrate__divider {\n\t\t\twidth: 1px;\n\t\t\theight: 12px;\n\t\t\tbackground-color: var(--border-sub);\n\t\t}\n\t\t.libra-winrate__count {\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tgap: 4px;\n\t\t}\n\t\t.libra-winrate__win {\n\t\t\tfont-family: var(--font-mono);\n\t\t\tfont-weight: var(--weight-semibold);\n\t\t\tcolor: var(--up);\n\t\t\tfont-variant-numeric: tabular-nums;\n\t\t}\n\t\t.libra-winrate__loss {\n\t\t\tfont-family: var(--font-mono);\n\t\t\tfont-weight: var(--weight-semibold);\n\t\t\tcolor: var(--down);\n\t\t\tfont-variant-numeric: tabular-nums;\n\t\t}\n\t\t.libra-winrate__label {\n\t\t\tcolor: var(--text-tertiary);\n\t\t}\n\t</style><div class=\"libra-winrate\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, attrs)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "><div class=\"libra-winrate__ring\"><svg class=\"libra-winrate__svg\" viewBox=\"0 0 100 100\"><circle cx=\"50\" cy=\"50\" r=\"45\" fill=\"none\" stroke=\"var(--border-main)\" stroke-width=\"8\"></circle> <circle cx=\"50\" cy=\"50\" r=\"45\" fill=\"none\" stroke=\"var(--up)\" stroke-width=\"8\" stroke-linecap=\"round\" stroke-dasharray=\"282.743\" stroke-dashoffset=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%.3f", 282.743-(props.WinRate/100.0)*282.743))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/winratecard.templ`, Line: 89, Col: 89}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"></circle></svg><div class=\"libra-winrate__center\"><span class=\"libra-winrate__percent\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f%%", props.WinRate))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/winratecard.templ`, Line: 93, Col: 79}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span></div></div><div class=\"libra-winrate__counts\"><div class=\"libra-winrate__count\"><span class=\"libra-winrate__win\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(props.WinCount)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/winratecard.templ`, Line: 98, Col: 53}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span> <span class=\"libra-winrate__label\">盈</span></div><div class=\"libra-winrate__divider\"></div><div class=\"libra-winrate__count\"><span class=\"libra-winrate__loss\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(props.LossCount)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/winratecard.templ`, Line: 103, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span> <span class=\"libra-winrate__label\">亏</span></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
