// build.rs — 编译时读取 design-tokens.json，生成 src/generated.rs
//
// 生成内容：
//   RAW_TOKENS_JSON: &str — 原始 JSON 字符串，供运行时 CSS 生成使用
//
// 路径约定：build.rs 的 CWD 为 crate 根目录 (packages/rust-tokens/)
//   设计令牌源文件：../../tokens/design-tokens.json
//   输出目标：src/generated.rs

use std::env;
use std::fs;
use std::path::Path;

/// 计算 Rust raw string literal 所需的最小 `#` 分隔符数量。
///
/// `r#"..."#` 要求内容中不含 `"#`。
/// `r##"..."##` 要求内容中不含 `"##`，以此类推。
fn needed_hash_count(s: &str) -> usize {
    for n in 1..10 {
        let pat = format!("\"{}", "#".repeat(n));
        if !s.contains(&pat) {
            return n;
        }
    }
    panic!("JSON 中包含连续 10 个 \"#，无法用 raw string literal 安全嵌入");
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set");
    let json_path = Path::new(&manifest_dir)
        .join("../../tokens/design-tokens.json");
    let json_str = fs::read_to_string(&json_path)
        .unwrap_or_else(|e| panic!("无法读取设计令牌文件 {:?}: {}", json_path, e));

    let hash_count = needed_hash_count(&json_str);
    let hashes: String = std::iter::repeat('#').take(hash_count).collect();

    let generated = format!(
        "// Auto-generated by build.rs from ../../tokens/design-tokens.json\n\
         // Do not edit manually.\n\n\
         /// The raw JSON content of design-tokens.json\n\
         pub const RAW_TOKENS_JSON: &str = r{hashes}\"{json_str}\"{hashes};\n",
        hashes = hashes,
        json_str = json_str,
    );

    let output_path = Path::new(&manifest_dir).join("src/generated.rs");
    fs::write(&output_path, generated)
        .unwrap_or_else(|e| panic!("无法写入 {:?}: {}", output_path, e));

    // 告知 Cargo 只有在源文件变更时才重新运行 build.rs
    println!("cargo:rerun-if-changed=../../tokens/design-tokens.json");
}
